import { useState } from 'react'
import { motion } from 'framer-motion'
import { FileText, Download, RefreshCw, CheckCircle, Palette, Settings, Users } from 'lucide-react'
import { jsPDF } from 'jspdf'
import '../styles/pdfgenerator.css'

function PDFGenerator({ portfolio, products, onReset }) {
  const [isGenerating, setIsGenerating] = useState(false)
  const [generated, setGenerated] = useState(false)
  const [settings, setSettings] = useState({
    includeScreenshots: true,
    includeMetrics: true,
    colorTheme: 'coral',
    font: 'satoshi',
    sections: {
      summary: true,
      projects: true,
      features: true,
      products: true,
    }
  })

  const themes = [
    { id: 'coral', name: 'Coral', color: '#E94560' },
    { id: 'blue', name: 'Ocean', color: '#0066CC' },
    { id: 'green', name: 'Forest', color: '#00A86B' },
    { id: 'purple', name: 'Violet', color: '#8B5CF6' },
    { id: 'dark', name: 'Midnight', color: '#1A1A2E' },
  ]

  const handleGeneratePDF = async () => {
    setIsGenerating(true)

    try {
      const doc = new jsPDF()
      const pageWidth = doc.internal.pageSize.getWidth()
      const pageHeight = doc.internal.pageSize.getHeight()
      const margin = 20
      let y = margin

      // Get theme color
      const theme = themes.find(t => t.id === settings.colorTheme) || themes[0]
      const accentColor = theme.color

      // Title
      doc.setFillColor(accentColor)
      doc.rect(0, 0, pageWidth, 40, 'F')
      
      doc.setTextColor(255, 255, 255)
      doc.setFontSize(24)
      doc.setFont('helvetica', 'bold')
      doc.text('Upfolio AI', margin, 28)
      
      doc.setFontSize(12)
      doc.setFont('helvetica', 'normal')
      doc.text('Professional Portfolio', margin, 36)

      y = 55

      // Summary Section
      if (settings.sections.summary) {
        doc.setTextColor(0, 0, 0)
        doc.setFontSize(16)
        doc.setFont('helvetica', 'bold')
        doc.text('Executive Summary', margin, y)
        y += 10

        doc.setTextColor(80, 80, 80)
        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        
        const summaryText = portfolio?.summary || 'Professional portfolio generated by Upfolio AI'
        const summaryLines = doc.splitTextToSize(summaryText, pageWidth - margin * 2)
        doc.text(summaryLines, margin, y)
        y += summaryLines.length * 5 + 15
      }

      // Projects Section
      if (settings.sections.projects && portfolio?.entries?.length > 0) {
        doc.setTextColor(0, 0, 0)
        doc.setFontSize(16)
        doc.setFont('helvetica', 'bold')
        doc.text('Portfolio Projects', margin, y)
        y += 10

        portfolio.entries.forEach((entry, index) => {
          if (y > pageHeight - 60) {
            doc.addPage()
            y = margin
          }

          // Project title
          doc.setFontSize(12)
          doc.setFont('helvetica', 'bold')
          doc.setTextColor(0, 0, 0)
          doc.text(`${index + 1}. ${entry.title || 'Project'}`, margin, y)
          y += 7

          // Description
          doc.setFontSize(10)
          doc.setFont('helvetica', 'normal')
          doc.setTextColor(80, 80, 80)
          const descLines = doc.splitTextToSize(entry.description || '', pageWidth - margin * 2)
          doc.text(descLines, margin, y)
          y += descLines.length * 5 + 5

          // Technologies
          if (entry.technologies?.length > 0) {
            doc.setFontSize(9)
            doc.setTextColor(accentColor)
            doc.text(`Technologies: ${entry.technologies.join(', ')}`, margin, y)
            y += 6
          }

          // Duration
          if (entry.duration) {
            doc.setTextColor(100, 100, 100)
            doc.text(`Duration: ${entry.duration}`, margin, y)
            y += 6
          }

          // Metrics
          if (settings.includeMetrics && entry.metrics?.length > 0) {
            y += 3
            entry.metrics.forEach(metric => {
              doc.setTextColor(0, 150, 100)
              doc.text(`✓ ${metric}`, margin + 5, y)
              y += 5
            })
          }

          y += 10
        })
      }

      // Features Section
      if (settings.sections.features) {
        if (y > pageHeight - 40) {
          doc.addPage()
          y = margin
        }

        doc.setTextColor(0, 0, 0)
        doc.setFontSize(16)
        doc.setFont('helvetica', 'bold')
        doc.text('Key Capabilities', margin, y)
        y += 10

        const capabilities = [
          'Full-stack web application development',
          'RESTful API design and integration',
          'Responsive UI/UX implementation',
          'Database design and optimization',
          'Agile development methodology',
        ]

        doc.setFontSize(10)
        doc.setFont('helvetica', 'normal')
        doc.setTextColor(80, 80, 80)
        
        capabilities.forEach(cap => {
          doc.text(`• ${cap}`, margin + 5, y)
          y += 6
        })
      }

      // Footer
      doc.setFillColor(240, 240, 240)
      doc.rect(0, pageHeight - 20, pageWidth, 20, 'F')
      
      doc.setTextColor(150, 150, 150)
      doc.setFontSize(8)
      doc.text('Generated by Upfolio AI | upfolio.ai', margin, pageHeight - 8)

      // Download
      doc.save('upfolio-portfolio.pdf')
      setGenerated(true)
    } catch (error) {
      console.error('PDF generation failed:', error)
    } finally {
      setIsGenerating(false)
    }
  }

  return (
    <div className="pdf-generator">
      <div className="results-card">
        <div className="results-card-header">
          <h3>
            <FileText size={20} />
            Export Portfolio
          </h3>
        </div>

        {/* Theme Selection */}
        <div className="pdf-section">
          <h4>
            <Palette size={16} />
            Color Theme
          </h4>
          <div className="pdf-themes">
            {themes.map(theme => (
              <button
                key={theme.id}
                className={`pdf-theme ${settings.colorTheme === theme.id ? 'active' : ''}`}
                onClick={() => setSettings({ ...settings, colorTheme: theme.id })}
                style={{ '--theme-color': theme.color }}
              >
                {settings.colorTheme === theme.id && <CheckCircle size={14} />}
              </button>
            ))}
          </div>
        </div>

        {/* Sections */}
        <div className="pdf-section">
          <h4>
            <Settings size={16} />
            Include Sections
          </h4>
          <div className="pdf-sections">
            {Object.entries(settings.sections).map(([key, value]) => (
              <label key={key} className="pdf-section-toggle">
                <input
                  type="checkbox"
                  checked={value}
                  onChange={() => setSettings({
                    ...settings,
                    sections: { ...settings.sections, [key]: !value }
                  })}
                />
                <span className="toggle-label">
                  {key.charAt(0).toUpperCase() + key.slice(1)}
                </span>
              </label>
            ))}
          </div>
        </div>

        {/* Options */}
        <div className="pdf-section">
          <h4>
            <Users size={16} />
            Options
          </h4>
          <div className="pdf-sections">
            <label className="pdf-section-toggle">
              <input
                type="checkbox"
                checked={settings.includeScreenshots}
                onChange={() => setSettings({ 
                  ...settings, 
                  includeScreenshots: !settings.includeScreenshots 
                })}
              />
              <span className="toggle-label">Include product screenshots</span>
            </label>
            <label className="pdf-section-toggle">
              <input
                type="checkbox"
                checked={settings.includeMetrics}
                onChange={() => setSettings({ 
                  ...settings, 
                  includeMetrics: !settings.includeMetrics 
                })}
              />
              <span className="toggle-label">Include success metrics</span>
            </label>
          </div>
        </div>

        {/* Generate Button */}
        <div className="pdf-actions">
          <button
            className="btn btn-primary pdf-generate-btn"
            onClick={handleGeneratePDF}
            disabled={isGenerating}
          >
            {isGenerating ? (
              <>
                <RefreshCw size={18} className="spinning" />
                Generating...
              </>
            ) : generated ? (
              <>
                <CheckCircle size={18} />
                Downloaded!
              </>
            ) : (
              <>
                <Download size={18} />
                Generate PDF
              </>
            )}
          </button>

          <button 
            className="btn btn-secondary"
            onClick={onReset}
          >
            <RefreshCw size={16} />
            New Analysis
          </button>
        </div>
      </div>
    </div>
  )
}

export default PDFGenerator